#include "lexicon.h"
#include "types.h"

static const char *det[] = {"the",     "a",       "my",    "your", "our",
                            "his",     "her",     "their", "this", "that",
                            "every",   "another", "some",  "no",   "either",
                            "neither", "yon"};
static const char *n[] = {"cat",
                          "dog",
                          "wankstain",
                          "fun",
                          "lady",
                          "mink",
                          "Hare Krishna",
                          "shrine maiden",
                          "Bar Mitzvah",
                          "ontologist",
                          "war criminal",
                          "paralegal",
                          "shaman",
                          "middle manager",
                          "Freemason",
                          "croissant",
                          "teacher",
                          "electrician",
                          "cryptobro",
                          "lifestyle coach",
                          "cannibal",
                          "exorcist",
                          "barista",
                          "apple",
                          "editor",
                          "therapist",
                          "uncle",
                          "oat milk enthusiast",
                          "obituary writer",
                          "friend",
                          "nun",
                          "astrophysicist",
                          "anarchist",
                          "intern",
                          "novelist",
                          "emotional support animal",
                          "landlord",
                          "podcaster",
                          "necromancer",
                          "influencer",
                          "warlord",
                          "cult leader",
                          "venture capitalist",
                          "TA",
                          "deacon",
                          "mortician",
                          "stenographer",
                          "barnacle",
                          "linguist",
                          "archbishop",
                          "raccoon",
                          "vampire",
                          "ghostwriter",
                          "lobbyist",
                          "TikToker",
                          "tax auditor",
                          "monk",
                          "stockbroker",
                          "goblin",
                          "doula",
                          "scoutmaster",
                          "mailman",
                          "demonologist",
                          "youth pastor",
                          "intern's uncle",
                          "substitute teacher",
                          "war photographer",
                          "pirate",
                          "actuary",
                          "golem",
                          "city councilman",
                          "exterminator",
                          "hedge fund manager",
                          "barbarian",
                          "speech therapist",
                          "alderman",
                          "necromancer's apprentice",
                          "yoga instructor",
                          "crossing guard",
                          "sommelier",
                          "exiled prince",
                          "court jester",
                          "middle school principal",
                          "forensic accountant",
                          "Bigfoot researcher",
                          "cruise director",
                          "funeral clown",
                          "minor deity",
                          "shaman's intern",
                          "troll",
                          "gynecologist",
                          "chiropractor",
                          "anime girl"};
static const char *n_name[] = {
    "Reimu Hakurei", "Jerry Seinfeld",     "Sayaka Miki",
    "Homura Akemi",  "General Butt Naked", "Michael Richards",
    "Idi Amin",      "Elijah Mohammad",    "Wallace D. Fard",
    "Sanae Kochiya", "DJ Scott Brown",     "S3RL",
    "DJ Income Tax", "Prester John"};
static const char *v_trans[] = {"abducts",        "baptizes",
                                "commodifies",    "debriefs",
                                "defunds",        "delegitimizes",
                                "destabilizes",   "doxes",
                                "embezzles from", "endorses",
                                "eulogizes",      "franchises",
                                "grooms",         "haunts",
                                "headhunts",      "homeschools",
                                "indoctrinates",  "invoices",
                                "lambastes",      "launders",
                                "lobbies",        "mansplains to",
                                "micromanages",   "misquotes",
                                "nationalizes",   "negs",
                                "out-sources",    "pardons",
                                "patronizes",     "platforms",
                                "privatizes",     "psychoanalyzes",
                                "publishes",      "recruits",
                                "rehabilitates",  "repatriates",
                                "reschedules",    "surveils",
                                "traumatizes",    "unfollows",
                                "unionizes",      "weaponizes",
                                "deplatforms",    "subpoenas",
                                "exorcises",      "canonizes",
                                "excommunicates", "deposes",
                                "annexes",        "ghostwrites for",
                                "subtweets",      "blacklists",
                                "gaslights",      "stonewalls",
                                "deepfakes",      "reincarnates",
                                "unalives",       "monetizes",
                                "deconstructs",   "essentializes",
                                "fetishizes",     "litigates against",
                                "annotates",      "exhumes",
                                "radicalizes",    "deradicalizes",
                                "infantilizes",   "fact-checks",
                                "memes about",    "subjugates",
                                "bewitches",      "summons",
                                "banishes",       "appraises",
                                "ostracizes",     "interrogates",
                                "embalms",        "unionized",
                                "outbids",        "overrules"};
static const char *v_intr[] = {
    "ascends",      "atones",         "capitulates",   "conspires",
    "converts",     "copes",          "defects",       "deflects",
    "deliberates",  "dissociates",    "evangelizes",   "filibusters",
    "fundraises",   "gatekeeps",      "gentrifies",    "grifts",
    "haunts",       "itemizes",       "laments",       "lingers",
    "litigates",    "lobbies",        "manifests",     "meditates",
    "microdoses",   "networks",       "overshares",    "persists",
    "pontificates", "procrastinates", "protests",      "rationalizes",
    "recuses",      "relapses",       "repents",       "resigns",
    "retreats",     "self-optimizes", "seethes",       "spirals",
    "testifies",    "transitions",    "unionizes",     "volunteers",
    "apostatizes",  "backslides",     "schisms",       "deconverts",
    "doomscrolls",  "manifests",      "tithes",        "monologues",
    "rage-quits",   "unravels",       "ascends again", "self-flagellates",
    "vanishes",     "reincarnates",   "germinates",    "decomposes",
    "implodes",     "transcends",     "self-isolates", "philosophizes",
    "fossilizes",   "schemes",        "molts",         "hibernates",
    "panics",       "recalibrates",   "secedes",       "fasts",
    "genuflects",   "absconds"};
static const char *adj[] = {"stupid",
                            "languid",
                            "pharisaic",
                            "bdelygmic",
                            "lithe",
                            "funny",
                            "post-ironic",
                            "depressed",
                            "moist",
                            "mediocre",
                            "incarcerated",
                            "unqualified",
                            "irresponsible",
                            "load-bearing",
                            "Scandinavian",
                            "compromised",
                            "peer-reviewed",
                            "lukewarm",
                            "ambitious",
                            "offensive",
                            "unavailable",
                            "undercooked",
                            "burdened",
                            "radicalised",
                            "uninvited",
                            "earnest",
                            "litigious",
                            "feral",
                            "sanctimonious",
                            "unhinged",
                            "telegenic",
                            "excommunicated",
                            "millenarian",
                            "tenured",
                            "untenured",
                            "gluten-free",
                            "performative",
                            "extrajudicial",
                            "uninsured",
                            "haunted",
                            "vestigial",
                            "bureaucratic",
                            "apocryphal",
                            "indictable",
                            "self-radicalized",
                            "embalmed",
                            "feudal",
                            "litigated",
                            "anointed",
                            "decommissioned",
                            "unbaptized",
                            "overqualified",
                            "schismatic",
                            "subpoenaed",
                            "extant",
                            "fungible",
                            "carcinogenic",
                            "exiled",
                            "hexed",
                            "indistinguishable",
                            "unconsecrated",
                            "nonbinary-coded",
                            "redacted",
                            "premillennial",
                            "post-apocalyptic",
                            "feudalistic",
                            "uncanonical",
                            "exegetical",
                            "dissociative",
                            "unlicensed",
                            "litigation-prone",
                            "self-anointed",
                            "carbonated",
                            "unkosher"};
static const char *adv[] = {
    "suddenly",     "secretly",       "offensively",     "furiously",
    "sexily",       "ironically",     "biblically",      "litigiously",
    "ominously",    "performatively", "posthumously",    "unceremoniously",
    "spiritually",  "tactically",     "apocalyptically", "passive-aggressively",
    "ceremonially", "compulsively",   "begrudgingly",    "unrepentantly",
    "theatrically", "categorically",  "metaphysically",  "vindictively"};
static const char *p[] = {
    "about",      "above",   "across",     "after",   "against", "along",
    "amid",       "among",   "around",     "at",      "before",  "behind",
    "below",      "beneath", "beside",     "between", "beyond",  "by",
    "despite",    "down",    "during",     "except",  "for",     "from",
    "in",         "inside",  "into",       "near",    "of",      "off",
    "on",         "onto",    "out of",     "outside", "over",    "past",
    "since",      "through", "throughout", "to",      "toward",  "under",
    "underneath", "until",   "upon",       "via",     "with",    "within",
    "without"};
static const char *c_n[] = {"that", "who", "whom", "whose", "which"};
static const char *conj_c[] = {
    "and",         "while", "although",      "because",   "whenever",
    "unless",      "until", "since",         "though",    "if",
    "even though", "once",  "provided that", "as though", "lest"};
static const char *conj_p[] = {"and", "or"};

const lexicon_dictionary lexicon[] = {{Det, det, ARRAY_SIZE(det)},
                                      {N, n, ARRAY_SIZE(n)},
                                      {N_name, n_name, ARRAY_SIZE(n_name)},
                                      {V_trans, v_trans, ARRAY_SIZE(v_trans)},
                                      {V_intr, v_intr, ARRAY_SIZE(v_intr)},
                                      {Adj, adj, ARRAY_SIZE(adj)},
                                      {Adv, adv, ARRAY_SIZE(adv)},
                                      {P, p, ARRAY_SIZE(p)},
                                      {C_n, c_n, ARRAY_SIZE(c_n)},
                                      {Conj_c, conj_c, ARRAY_SIZE(conj_c)},
                                      {Conj_p, conj_p, ARRAY_SIZE(conj_p)},
                                      {0, NULL, 0}};